# Generated by Django 5.0.3 on 2024-04-28 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clients_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clients',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='clients_avatar'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='clients',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='phonenumbers',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
