# Generated by Django 5.0.3 on 2024-04-29 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_clients_description_alter_clients_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
    ]
